name: mado_translation
description: Offline Translator (Arabic ↔ English ↔ German) + OCR
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_mlkit_translation: ^0.10.0
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

