name: Unpack Flutter App

on:
  workflow_dispatch:

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Make folders
        run: |
          mkdir -p lib
          mkdir -p android/app/src/main

      - name: Extract pubspec.yaml
        run: |
          awk '/=== FILE: pubspec.yaml ===/{flag=1;next}/=== FILE:/{flag=0}flag' project_files.txt > pubspec.yaml

      - name: Extract main.dart
        run: |
          awk '/=== FILE: lib\/main.dart ===/{flag=1;next}/=== FILE:/{flag=0}flag' project_files.txt > lib/main.dart

      - name: Extract README.md
        run: |
          awk '/=== FILE: README.md ===/{flag=1;next}/=== FILE:/{flag=0}flag' project_files.txt > README.md

      - name: Patch AndroidManifest.xml
        run: |
          awk '/=== FILE: android\/app\/src\/main\/AndroidManifest.xml/{flag=1;next}/=== FILE:/{flag=0}flag' project_files.txt > manifest_additions.xml
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if [ -s manifest_additions.xml ] && [ -f "$MANIFEST" ]; then
            perms="$(cat manifest_additions.xml)"
            # نبني ملف جديد: السطر الأول كما هو، بعدها الصلاحيات، ثم باقي الملف
            { head -n 1 "$MANIFEST"; echo "$perms"; tail -n +2 "$MANIFEST"; } > tmp_manifest.xml
            mv tmp_manifest.xml "$MANIFEST"
            echo "Manifest patched with permissions."
          else
            echo "No manifest additions or manifest missing, skipping."
          fi

      - name: Flutter pub get
        run: flutter pub get

     # - name: Commit changes
      #  run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Unpacked project_files.txt into Flutter app" || echo "No changes"
          git push
